# Generated by Django 4.1.5 on 2023-02-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=250)),
                ('city_name_rod', models.CharField(max_length=250)),
                ('slug_city', models.SlugField(max_length=250, unique=True, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='Fence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fence_text_description', models.TextField()),
                ('fence_name', models.TextField()),
                ('fence_picture', models.ImageField(upload_to='fences')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_customer', models.CharField(max_length=100)),
                ('text_request', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
