# Generated by Django 4.1.5 on 2023-02-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fence',
            name='fence_slug',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
