# Generated by Django 4.1.5 on 2023-02-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0002_fence_fence_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='request_data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='name_customer',
            field=models.CharField(max_length=100, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='text_request',
            field=models.TextField(verbose_name='Комментарий'),
        ),
    ]
