# Generated by Django 4.1.5 on 2023-03-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0003_requests_request_data_alter_requests_name_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.TextField()),
                ('video_describe', models.TextField()),
                ('video_path', models.TextField()),
            ],
        ),
    ]
