# Generated by Django 4.1.5 on 2023-03-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0004_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
