# Generated by Django 4.1.5 on 2023-03-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0005_video_video_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
